const mongoose = require('mongoose');

const serverRegistrationSchema = new mongoose.Schema({
  SerId: { type: String, required: true },
  SerName: { type: String, required: true },
  hostname: { type: String, required: true },
  SerType: { type: String, enum: ['Rack Server', 'Blade Server', 'Tower Server', 'Mainframe'], required: true },
  manufacturer: { type: String, enum: ['Dell', 'HPE', 'Lenovo', 'IBM', 'Huawei', 'Cisco', 'Supermicro'], required: true },
  model: { type: String, required: true },
  serialNumber: { type: String, required: true },
  assetTag: { type: String, required: true },
  ownerDepartment: { type: String, enum: ['Infrastructure', 'Data Center', 'IT Operations', 'Application Development', 'Database Administration'], required: true },
  primaryOwner: { type: String, required: true },
  primaryContact: { type: String, required: true },
  secondaryOwner: { type: String },
  secondaryContact: { type: String },
  supportVendor: { type: String },
  dataCenter: { type: String, enum: ['DC1', 'DC2', 'DR Site', 'Branch Office'], required: true },
  rackId: { type: String, required: true },
  rackPosition: { type: String, required: true },
  roomFloor: { type: String, required: true },
  geoCoordinates: { type: String, required: true },
  cpuType: { type: String, required: true },
  cpuSockets: { type: Number, required: true },
  coresPerCpu: { type: Number, required: true },
  logicalProcessors: { type: Number, required: true },
  ramCapacity: { type: String, required: true },
  storageCapacity: { type: String, required: true },
  raidConfig: { type: String, required: true },
  powerSupplies: { type: String, required: true },
  os: { type: String, enum: ['Windows Server 2022', 'RHEL 9', 'Ubuntu Server 22.04', 'SUSE Linux Enterprise Server', 'VMware ESXi'], required: true },
  osLicense: { type: String, required: true },
  firmwareVersion: { type: String, required: true },
  nics: { type: Number, required: true },
  nicSpeed: { type: String, enum: ['1GbE', '10GbE', '25GbE', '40GbE', '100GbE'] },
  clusterMembership: { type: String, enum: ['No', 'Yes'] },
  clusterName: { type: String },
  upstreamDependencies: { type: String },
  downstreamDependencies: { type: String },
  associatedServices: { type: String },
  businessCriticality: { type: String, enum: ['High', 'Medium', 'Low'], required: true },
  serviceImpact: { type: String },
  riskRating: { type: String, enum: ['High', 'Medium', 'Low'], required: true },
  licenseType: { type: String, enum: ['OEM', 'Volume License', 'Subscription'], required: true },
  licenseExpiry: { type: Date },
  supportContract: { type: String, enum: ['No', 'Yes'] },
  contractExpiry: { type: Date },
  complianceRequirements: { type: String },
  monitoringTool: { type: String },
  lastMaintenance: { type: Date },
  nextMaintenance: { type: Date },
  firmwareHistory: { type: String },
  incidentHistory: { type: String },
  lifecycleStatus: { type: String, enum: ['Planned', 'Active', 'In Maintenance', 'Retired'], required: true },
  commissionDate: { type: Date },
  decommissionDate: { type: Date },
  addedToCmdb: { type: Date },
  lastUpdated: { type: Date }
}, { timestamps: true });

module.exports = mongoose.model('ServerRegistration', serverRegistrationSchema);